# Generated by Django 4.1.3 on 2023-03-02 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_classic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicsystemuser',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
